### ISSUE TITLE
Plugins persistence between container restarts

### ISSUE THREAD

**Issue by MatteoManzoni** [SteveMcGrath/docker-nessus_scanner#17]
Hi,
We are using your image to deploy our containerized SC managed Nessus scanner.
There is any way to save on persistent storage (we are using kubernetes and we are able to work with PVCs) the plugins to prevent recompilation upon restart of the container?

Thank you,
Matteo Manzoni

**Comment by Yrok472** [comment]
@MatteoManzoni 

Hi, i solved this problem

https://github.com/Yrok472/docker-nessus_scanner
https://hub.docker.com/repository/docker/yrok472/nessus_scanner

Introduced "PRODUCT_INITIALIZATION" option

Perform first deployment start with "PRODUCT_INITIALIZATION"=true

Your pvc should be mount by next path - `/opt/nessus/`
Update deployment, set "PRODUCT_INITIALIZATION"=false

Full Example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus
  namespace: <custom>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessus
  template:
    metadata:
      namespace: <custom>
      labels:
        app: nessus
    spec:
      containers:
        - name: nessus
          livenessProbe:
            httpGet:
              path: /
              port: 8834
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8834
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          image: yrok472/nessus_scanner:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8834
          env:
            - name: LINKING_KEY
              value: "<key>"
            - name: SCANNER_NAME
              value: "<name>"
            - name: PRODUCT_INITIALIZATION
              value: "false"
            - name: ADMIN_USER
              value: "admin"
            - name: ADMIN_PASS
              value: "changeme"
          volumeMounts:
            - mountPath: "/opt/nessus/"
              name: nessus-vol
      volumes:
        - name: nessus-vol
          persistentVolumeClaim:
            claimName: nessus-pvc
```

**Comment by MatteoManzoni** [comment]
I have found another way with the use of a init container but thanks anyway

**Comment by egkelly** [comment]
> I have found another way with the use of a init container but thanks anyway

Do you mind sharing what worked for you? I've implemented an init container with a shared volume mounted to /opt/nessus/var/nessus, but the resulting container still recompiles nessus and breaks.

**Comment by MatteoManzoni** [comment]
Hey @egkelly, here the snippet that I was using, the init container is just an hack to force recompilation if the Nessus version changes or something messed up the PVC
``` yaml
      initContainers:
        - name: nessus-firstrun-setupper
          image: <nessus-image>
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          command:
          - /bin/bash
          - -c
          - >
              CURRENT_VERSION="$(/new-setup/sbin/nessusd -h | grep 'nessusd, version' | awk '{print $3}')";
              NEW_VERSION="$(/opt/nessus/sbin/nessusd -h | grep 'nessusd, version' | awk '{print $3}')";

              if [ ! -f "/opt/nessus/configured" ] || [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then 
                echo "Nessus version mismatch or not configured... Configuring it";
                rm -rf /new-setup/*; 
                cp -r /opt/nessus/. /new-setup;
                touch /new-setup/configured; 
              else
                echo "The nessus PVC seems already configured, and on the correct version... Skipping";
              fi
          volumeMounts:
            - mountPath: "/new-setup/"
              name: nessus-opt 
      containers:
        - name: nessus-scanner
          image: <nessus-image>
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 150m
              memory: 400Mi
            limits:
              cpu: 2000m
              memory: 1000Mi
          ports:
          ...
          env:
          ...
          volumeMounts:
            - mountPath: "/opt/nessus/"
              name: nessus-opt
            - mountPath: /opt/nessus/etc/nessus/nessusd.rules
              name: nessusd-rules
              subPath: nessusd.rules
      volumes:
        - name: nessus-opt
          persistentVolumeClaim:
            claimName: nessus-opt-pvc
        - configMap:
            defaultMode: 420
            items:
            - key: nessusd.rules
              path: nessusd.rules
            name: nessusd-rules
          name: nessusd-rules
```
