### ISSUE TITLE
nessus-services could not be found. Install it and try again 

### ISSUE THREAD

**Issue by adammike** [SteveMcGrath/docker-nessus_scanner#5]
Trying to create a kubernetes deployment using this image and I am seeing this when using the `8.3.0` tag.

Any suggestions?

```
$ kubectl logs nessus-scanner-768597987d-qpzxg
-- Starting the Nessus service as root
[Sat Apr  6 02:01:25 2019][7.1] **** nessus-services could not be found. Install it and try again 
nessusd (Nessus) 8.3.0 [build 20187] for Linux
Copyright (C) 1998 - 2019 Tenable, Inc.

[Sat Apr  6 02:01:25 2019][8.1] **** nessus-services could not be found. Install it and try again 
nessusd (Nessus) 8.3.0 [build 20187] for Linux
Copyright (C) 1998 - 2019 Tenable, Inc.

....snip...

[Sat Apr  6 02:03:06 2019][134.1] **** nessus-services could not be found. Install it and try again 
nessusd (Nessus) 8.3.0 [build 20187] for Linux
Copyright (C) 1998 - 2019 Tenable, Inc.

[Sat Apr  6 02:03:06 2019][135.1] **** nessus-services could not be found. Install it and try again 
nessusd (Nessus) 8.3.0 [build 20187] for Linux
Copyright (C) 1998 - 2019 Tenable, Inc.

nessusd exited with too many fatal errors. Exiting
```

My deployment YAML looks like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-04-06T01:55:18Z"
  generation: 1
  labels:
    app: nessus-scanner
    chart: nessus-scanner-0.1.0
    heritage: Tiller
    release: nessus-scanner
  name: nessus-scanner
  namespace: myns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nessus-scanner
      release: nessus-scanner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nessus-scanner
        release: nessus-scanner
    spec:
      containers:
      - env:
        - name: SCANNER_NAME
          value: nessus.scanner.name
        - name: SECURITYCENTER
          value: "Yes"
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin_user
              name: nessus-scanner-secrets
        - name: ADMIN_PASS
          valueFrom:
            secretKeyRef:
              key: admin_pass
              name: nessus-scanner-secrets
        image: stevemcgrath/nessus_scanner:8.3.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: nessus
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nessus-scanner
        ports:
        - containerPort: 8834
          name: nessus
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: nessus
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/nessus/var/nessus
          name: optnessusvarnessus
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: optnessusvarnessus
        persistentVolumeClaim:
          claimName: nessus-scanner-storage
```
