### ISSUE TITLE
Scans don't start 

### ISSUE THREAD

**Issue by gevalter** [SteveMcGrath/docker-nessus_scanner#6]
Hey guys, I want to launch an internal PCI scan on our servers. So I deployed this image and configured it inside our kubernetes cluster. 

I can see the scanner in tenable.io, it says it's online but the scans don't work, it just enter a pending stage and aborting after 1 hour. In the plugin section of the scanner it says N/A. 

This is my deployment yaml:

```
---
apiVersion: v1
kind: Service
metadata:
  name: nessus-scanner
spec:
  selector:
    app: nessus-scanner
  ports:
    - port: 3020
      name: http
      targetPort: nessus-scanner
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessus-scanner
  labels:
    app: nessus-scanner
spec:
  replicas: 1
  progressDeadlineSeconds: 180
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nessus-scanner
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nessus-scanner
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nessus-scanner
        image: stevemcgrath/nessus_scanner
        ports:
        - containerPort: 3020
          name: nessus-scanner
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: "LINKING_KEY"
            value: "XXXXXXXXXXXXXXXXCXXXXXXXXXXXXXXX"
          - name: SCANNER_NAME
            value: sunbit-kube-internal
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: admin_user
                name: nessus-scanner-secrets
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                key: admin_pass
                name: nessus-scanner-secrets
```

Now i don't know if i need to set ingress here so tenable.cloud.com would have an ip it can access because right now i don't to which ip the tenable.cloud try to use.
